### ISSUE TITLE
_mm512_reduce_add_ps and friends are setting fast-math flags they should not set

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/stdarch#1533] opened 2024-02-17 13:16 UTC
Today I learned about the existence of the `simd_reduce_add_unordered` intrinsic. When called on a float, this compiles to LLVM's `vector.reduce.fadd` with the "fast" flag set, which means that passing in NAN or INF is UB and optimizations are allowed "to treat the sign of a zero argument or zero result as insignificant" (which I think means the sign of input zeros is non-deterministically swapped and returned zeros have non-deterministic sign).

This intrinsic is not used a lot in stdarch, but it has a total of 8 uses (all in `avx512f.rs`). 4 of these are integer intrinsics, where this should be entirely equivalent to `simd_reduce_add`; not sure why the "unordered" version is used. The other 4 are float intrinsics, `_mm512_reduce_add_ps` being the first:

https://github.com/rust-lang/stdarch/blob/4d9c0bb591336792c4c4baf293d0acc944e57e28/crates/core_arch/src/x86/avx512f.rs#L31262-L31270
```rust
/// Reduce the packed single-precision (32-bit) floating-point elements in a by addition. Returns the sum of all elements in a.
///
/// [Intel's documentation](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm512_reduce_add_ps&expand=4562)
#[inline]
#[target_feature(enable = "avx512f")]
#[unstable(feature = "stdarch_x86_avx512", issue = "111137")]
pub unsafe fn _mm512_reduce_add_ps(a: __m512) -> f32 {
    simd_reduce_add_unordered(a.as_f32x16())
}
```

Neither the docs here nor Intel's docs mention that this is UB on NAN or INF, and the concerns around signed zeros and doing the addition in an unspecified order. Given that the Intel docs should be the authoritative docs (since this is a vendor intrinsic), why is it even correct to use fast-math flags here? Either the docs need to be updated to state the fast-math preconditions, or the implementation needs to be updated to avoid the fast-math flag. Maybe it should only use "reassoc", not the full but unsafe "fast" flag? But even that should probably be mentioned in the docs.

**Comment by Amanieu** [comment] 2024-02-18 15:30
It is definitely incorrect for these intrinsics to be using the fast-math flag.

Here is the LLVM IR that clang generates for this intrinsic:
```llvm
%0 = tail call reassoc noundef float @llvm.vector.reduce.fadd.v16f32(float -0.000000e+00, <16 x float> %x)
```

**Comment by RalfJung** [comment] 2024-02-18 22:02
That allows LLVM to add the elements in any order, and also do re-association optimizations when the result is fed into another `reassoc` function. I don't see how that matches the [Intel docs](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm512_reduce_add_ps%252525252525252520&expand=133&ig_expand=5303).

**Comment by RalfJung** [comment] 2024-02-21 07:33
Specifically, if I were to do something like
```rust
let sum = _mm512_reduce_add_ps(a);
let vec = _mm512_set_pd(sum, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0);
let sum2 = _mm512_reduce_add_ps(vec);
````
then in my reading of `reassoc`, LLVM would be allowed to arbitrarily reorder all the 15 elements being summed up here when computing `sum2`. There's nothing that constrains it to only reassociate "within" a single `_mm512_reduce_add_ps`.

I don't think this is a correct implementation of the Intel vendor intrinsic.

**Comment by workingjubilee** [comment] 2024-02-21 08:24
I do not believe it is, no.

**Comment by workingjubilee** [comment] 2024-02-21 08:55
@nikic has confirmed to me that Ralf's concerns about `reassoc` being allowed to potentially do "basically whatever" are accurate, with the caveat that all the relevant operations have to be tagged with `reassoc`.

So yes, these are very _not_ correct implementations.

**Comment by workingjubilee** [comment] 2024-02-21 08:57
The problem is that the _lack_ of the `reassoc` doesn't seem to be correct either?

**Comment by RalfJung** [comment] 2024-02-21 09:01
Intel specifies a very specific order of summation. It's not left-to-right, which is what the no-reassoc version would do. From what I understand there is anyway no hardware operation that actually performs this particular kind of summation, so either LLVM needs to have support for this specific operation (and lower it to the best instruction sequence), or we need to do the lowering ourselves in the implementation of `_mm512_reduce_add_ps`.

**Comment by workingjubilee** [comment] 2024-02-21 09:09
@RalfJung Hmm. There are a few different possible sequences a compiler can use, but one of the "obvious" ones is a sequence that just repeatedly uses the "do one round of tree-reduction" instruction, which works like you might imagine from that description I just gave.

**Comment by nikic** [comment] 2024-02-21 09:12
Yes, in practice reassoc on reductions produces a tree reduction. Of course, this is not guaranteed from a semantics perspective.

**Comment by workingjubilee** [comment] 2024-02-21 09:27
@RalfJung fwiw, Niki mentions that "perform a tree reduction" was proposed in the past as a possible annotation for the reduces, so perhaps that's the tree we should be barking up this time.

**Comment by RalfJung** [comment] 2024-02-21 10:00
If that's a possibility then that would make most sense, yes -- have an intrinsic that reduces in a well-defined order that matches what the Intel docs say (i.e., tree reduction).

**Comment by RalfJung** [comment] 2024-02-22 06:34
My understanding is that clang generates the same IR, so we should probably file this as an LLVM issue as well. How does one call these intrinsics in C?

**Comment by Amanieu** [comment] 2024-02-23 17:14
> My understanding is that clang generates the same IR, so we should probably file this as an LLVM issue as well. How does one call these intrinsics in C?

https://godbolt.org/z/7Wbhjeo7n

**Comment by RalfJung** [comment] 2024-02-23 18:53
Thanks! Filed an issue: https://github.com/llvm/llvm-project/issues/82813

**Comment by RalfJung** [comment] 2024-02-25 10:35
@nikic it seems I don't know how to talk to LLVM people, they don't seem to agree with me on what it even means to have a LangRef. :/ Maybe you can help move the discussion in https://github.com/llvm/llvm-project/issues/82813 somewhere productive?

**Comment by sayantn** [comment] 2024-06-20 19:45
We can also not use `simd_reduce_add_unordered`, because as LLVM says (at least in LangRef), there is no guarantee of associativity in `vector.reduce.add`, so we can do what gcc does, and hand-code the reduce-add ourselves. I did a small implementation in Godbolt for `_mm512_reduce_add_ps` [here](https://godbolt.org/z/Esav56Ksa). It seems like LLVM is doing a spurious zero addition - I am no expert on floating point, but I think that addition with +0.0 is nop

**Comment by Amanieu** [comment] 2024-06-30 10:34
This is now fixed by https://github.com/rust-lang/stdarch/pull/1594: all of these are now implemented by explicitly expanding to a sequence of operations instead of using the LLVM intrinsics.

**Closed by Amanieu** 2024-06-30 10:34 UTC

**Comment by RalfJung** [comment] 2024-06-30 10:41
Should we remove the `unordered` intrinsics or are they still useful?

**Comment by Amanieu** [comment] 2024-07-02 09:47
They may still be useful for generic simd (cc @workingjubilee)
